# (C) Copyright 2024, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: sorru94
      url-base: https://github.com/sorru94

  projects:
    - name: zephyr
      remote: sorru94
      revision: heap-listeners
      import: true
    - name: astarte-device-sdk-zephyr
      remote: sorru94
      repo-path: astarte-device-sdk-zephyr.git
      path: astarte-device-sdk-zephyr
      revision: heap_statistics
      west-commands: scripts/west-commands.yml
      import: true
