# (C) Copyright 2024, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: astarte-platform
      url-base: https://github.com/astarte-platform
    - name: secomind
      url-base: https://github.com/secomind
    - name: sorru94
      url-base: https://github.com/sorru94

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.0.0
      import: true
    - name: astarte-device-sdk-zephyr
      remote: sorru94
      repo-path: astarte-device-sdk-zephyr.git
      path: astarte-device-sdk-zephyr
      revision: support-for-nRF7002
      west-commands: scripts/west-commands.yml
    - name: zlib-zephyr
      remote: sorru94
      revision: release-v1.3.1-no-crc32
      path: modules/zlib
