graph TD;
    edgehog_device_thread_entry_point-->edgehog_device_new;
    edgehog_device_new-->calloc;
    calloc-->malloc;
    malloc-->malloc_lock;
    malloc_lock-->z_impl_k_mutex_lock;
    z_impl_k_mutex_lock-->adjust_owner_prio;
    adjust_owner_prio-->z_thread_prio_set;
    z_thread_prio_set-->sys_dlist_remove;
    z_thread_prio_set-->update_cache;
    update_cache-->z_reset_time_slice;
    z_reset_time_slice-->z_abort_timeout;
    z_abort_timeout-->remove_timeout;
    z_reset_time_slice-->thread_is_sliceable;
    z_reset_time_slice-->z_add_timeout;
    z_add_timeout-->elapsed;
    elapsed-->sys_clock_elapsed;
    sys_clock_elapsed-->elapsed;
    z_add_timeout-->next_timeout;
    next_timeout-->elapsed;
    z_add_timeout-->sys_clock_set_timeout;
    sys_clock_set_timeout-->elapsed;
    z_impl_k_mutex_lock-->z_pend_curr;
    z_pend_curr-->add_to_waitq_locked;
    add_to_waitq_locked-->unready_thread;
    unready_thread-->sys_dlist_remove;
    unready_thread-->update_cache;
    z_pend_curr-->z_add_timeout;
    z_pend_curr-->arch_swap;
    z_impl_k_mutex_lock-->z_reschedule;
    z_reschedule-->arch_swap;
    malloc-->sys_heap_aligned_alloc;
    sys_heap_aligned_alloc-->sys_heap_alloc;
    sys_heap_alloc-->alloc_chunk;
    alloc_chunk-->bucket_idx;
    alloc_chunk-->chunk_size;
    chunk_size-->chunk_field;
    alloc_chunk-->free_list_remove_bidx;
    free_list_remove_bidx-->chunk_field;
    free_list_remove_bidx-->chunk_set;
    alloc_chunk-->chunk_field;
    sys_heap_alloc-->chunk_size;
    sys_heap_alloc-->split_chunks;
    split_chunks-->chunk_size;
    split_chunks-->set_chunk_size;
    set_chunk_size-->chunk_set;
    split_chunks-->chunk_set;
    sys_heap_alloc-->free_list_add;
    free_list_add-->chunk_size;
    free_list_add-->bucket_idx;
    free_list_add-->chunk_set;
    free_list_add-->chunk_field;
    sys_heap_alloc-->set_chunk_used;
    sys_heap_aligned_alloc-->alloc_chunk;
    sys_heap_aligned_alloc-->mem_to_chunkid;
    sys_heap_aligned_alloc-->split_chunks;
    sys_heap_aligned_alloc-->free_list_add;
    sys_heap_aligned_alloc-->chunk_size;
    sys_heap_aligned_alloc-->set_chunk_used;
    malloc-->__aeabi_read_tp;
    malloc-->malloc_unlock;
    malloc_unlock-->z_impl_k_mutex_unlock;
    z_impl_k_mutex_unlock-->adjust_owner_prio;
    z_impl_k_mutex_unlock-->z_unpend_first_thread;
    z_unpend_first_thread-->unpend_thread_no_timeout;
    unpend_thread_no_timeout-->sys_dlist_remove;
    z_unpend_first_thread-->z_abort_timeout;
    z_impl_k_mutex_unlock-->z_ready_thread;
    z_ready_thread-->ready_thread;
    ready_thread-->update_cache;
    z_impl_k_mutex_unlock-->z_reschedule;
    calloc-->__aeabi_read_tp;
    calloc-->memset;
    edgehog_device_new-->edgehog_settings_init;
    edgehog_settings_init-->settings_subsys_init;
    settings_subsys_init-->z_impl_k_mutex_lock;
    settings_subsys_init-->settings_init;
    settings_init-->settings_store_init;
    settings_subsys_init-->settings_backend_init;
    settings_backend_init-->flash_area_open;
    flash_area_open-->z_impl_device_is_ready;
    settings_backend_init-->flash_area_get_sectors;
    flash_area_get_sectors-->flash_area_open;
    flash_area_get_sectors-->flash_area_close;
    flash_area_get_sectors-->flash_page_foreach;
    settings_backend_init-->settings_nvs_backend_init;
    settings_nvs_backend_init-->nvs_mount;
    nvs_mount-->z_impl_k_mutex_init;
    nvs_mount-->z_impl_flash_get_page_info_by_offs;
    z_impl_flash_get_page_info_by_offs-->flash_get_page_info;
    nvs_mount-->z_impl_k_mutex_lock;
    nvs_mount-->nvs_al_size;
    nvs_mount-->z_impl_k_mutex_unlock;
    nvs_mount-->nvs_flash_cmp_const;
    nvs_flash_cmp_const-->nvs_flash_rd;
    nvs_mount-->nvs_sector_advance;
    nvs_mount-->nvs_recover_last_ate;
    nvs_recover_last_ate-->nvs_al_size;
    nvs_recover_last_ate-->nvs_flash_rd;
    nvs_recover_last_ate-->nvs_ate_valid;
    nvs_ate_valid-->nvs_al_size;
    nvs_ate_valid-->crc8_ccitt;
    nvs_mount-->nvs_flash_rd;
    nvs_mount-->nvs_flash_erase_sector;
    nvs_flash_erase_sector-->z_impl_flash_flatten;
    nvs_flash_erase_sector-->nvs_flash_cmp_const;
    nvs_mount-->nvs_ate_valid;
    nvs_mount-->nvs_gc;
    nvs_gc-->nvs_al_size;
    nvs_gc-->nvs_sector_advance;
    nvs_gc-->nvs_flash_rd;
    nvs_gc-->nvs_flash_erase_sector;
    nvs_gc-->nvs_prev_ate;
    nvs_prev_ate-->nvs_al_size;
    nvs_prev_ate-->nvs_flash_rd;
    nvs_prev_ate-->nvs_close_ate_valid;
    nvs_close_ate_valid-->nvs_ate_valid;
    nvs_close_ate_valid-->nvs_al_size;
    nvs_prev_ate-->nvs_recover_last_ate;
    nvs_gc-->nvs_ate_valid;
    nvs_gc-->nvs_ate_crc8_update;
    nvs_ate_crc8_update-->crc8_ccitt;
    nvs_gc-->nvs_flash_ate_wrt;
    nvs_flash_ate_wrt-->nvs_flash_al_wrt;
    nvs_flash_al_wrt-->__aeabi_memcpy;
    nvs_flash_al_wrt-->memset;
    nvs_flash_ate_wrt-->nvs_al_size;
    nvs_gc-->nvs_flash_al_wrt;
    nvs_gc-->nvs_add_gc_done_ate;
    nvs_add_gc_done_ate-->nvs_ate_crc8_update;
    nvs_add_gc_done_ate-->nvs_flash_ate_wrt;
    nvs_gc-->nvs_close_ate_valid;
    nvs_gc-->nvs_recover_last_ate;
    nvs_mount-->nvs_add_gc_done_ate;
    settings_nvs_backend_init-->nvs_read;
    nvs_read-->nvs_read_hist;
    nvs_read_hist-->nvs_al_size;
    nvs_read_hist-->nvs_prev_ate;
    nvs_read_hist-->nvs_ate_valid;
    nvs_read_hist-->nvs_flash_rd;
    settings_backend_init-->settings_src_register;
    settings_backend_init-->settings_dst_register;
    settings_subsys_init-->z_impl_k_mutex_unlock;
    edgehog_device_new-->uuid_generate_v4_string;
    uuid_generate_v4_string-->z_impl_sys_rand_get;
    z_impl_sys_rand_get-->xoshiro128_next;
    z_impl_sys_rand_get-->__aeabi_memcpy;
    z_impl_sys_rand_get-->sys_clock_cycle_get_32;
    sys_clock_cycle_get_32-->elapsed;
    uuid_generate_v4_string-->snprintf;
    snprintf-->memset;
    snprintf-->__l_vfprintf;
    __l_vfprintf-->strnlen;
    __l_vfprintf-->__ultoa_invert;
    edgehog_device_new-->edgehog_telemetry_new;
    edgehog_telemetry_new-->calloc;
    edgehog_telemetry_new-->edgehog_telemetry_destroy;
    edgehog_telemetry_destroy-->free;
    free-->malloc_lock;
    free-->sys_heap_free;
    sys_heap_free-->mem_to_chunkid;
    sys_heap_free-->set_chunk_used;
    sys_heap_free-->free_chunk;
    free_chunk-->chunk_size;
    free_chunk-->chunk_field;
    free_chunk-->free_list_remove;
    free_list_remove-->chunk_size;
    free_list_remove-->bucket_idx;
    free_list_remove-->free_list_remove_bidx;
    free_chunk-->merge_chunks;
    merge_chunks-->chunk_size;
    merge_chunks-->set_chunk_size;
    merge_chunks-->chunk_set;
    free_chunk-->free_list_add;
    free-->malloc_unlock;
    edgehog_telemetry_new-->__aeabi_memcpy;
    edgehog_telemetry_new-->edgehog_settings_load;
    edgehog_settings_load-->strlen;
    edgehog_settings_load-->snprintf;
    edgehog_settings_load-->settings_load_subtree_direct;
    settings_load_subtree_direct-->z_impl_k_mutex_lock;
    settings_load_subtree_direct-->z_impl_k_mutex_unlock;
    edgehog_telemetry_new-->telemetry_entry_new;
    telemetry_entry_new-->calloc;
    telemetry_entry_new-->k_timer_init;
    edgehog_telemetry_new-->set_telemetry_entry;
    set_telemetry_entry-->free;
    edgehog_device_new-->astarte_device_add_interface;
    astarte_device_add_interface-->introspection_update;
    introspection_update-->astarte_interface_validate;
    introspection_update-->find_node_by_name;
    find_node_by_name-->strncmp;
    introspection_update-->append_introspection_node;
    append_introspection_node-->calloc;
    edgehog_device_new-->free;
    edgehog_device_thread_entry_point-->edgehog_device_start;
    edgehog_device_start-->edgehog_ota_init;
    edgehog_ota_init-->memset;
    edgehog_ota_init-->edgehog_settings_load;
    edgehog_ota_init-->strlen;
    edgehog_ota_init-->pub_ota_event;
    pub_ota_event-->zbus_chan_pub;
    zbus_chan_pub-->k_is_in_isr;
    zbus_chan_pub-->sys_timepoint_calc;
    sys_timepoint_calc-->sys_clock_tick_get;
    sys_clock_tick_get-->elapsed;
    zbus_chan_pub-->chan_lock;
    chan_lock-->k_is_in_isr;
    chan_lock-->__aeabi_read_tp;
    chan_lock-->z_impl_k_thread_priority_get;
    chan_lock-->z_impl_k_thread_priority_set;
    z_impl_k_thread_priority_set-->z_thread_prio_set;
    z_impl_k_thread_priority_set-->z_reschedule_irqlock;
    z_reschedule_irqlock-->arch_swap;
    chan_lock-->z_impl_k_sem_take;
    z_impl_k_sem_take-->z_pend_curr;
    zbus_chan_pub-->__aeabi_memcpy;
    zbus_chan_pub-->_zbus_vded_exec;
    _zbus_vded_exec-->sys_timepoint_timeout;
    sys_timepoint_timeout-->sys_clock_tick_get;
    _zbus_vded_exec-->z_impl_k_msgq_put;
    z_impl_k_msgq_put-->z_unpend_first_thread;
    z_impl_k_msgq_put-->__aeabi_memcpy;
    z_impl_k_msgq_put-->z_ready_thread;
    z_impl_k_msgq_put-->z_reschedule;
    z_impl_k_msgq_put-->z_handle_obj_poll_events;
    z_handle_obj_poll_events-->signal_poll_event;
    signal_poll_event-->z_unpend_thread;
    z_unpend_thread-->unpend_thread_no_timeout;
    z_unpend_thread-->z_abort_timeout;
    signal_poll_event-->z_ready_thread;
    signal_poll_event-->z_abort_timeout;
    signal_poll_event-->z_work_submit_to_queue;
    z_work_submit_to_queue-->submit_to_queue_locked;
    submit_to_queue_locked-->k_is_in_isr;
    submit_to_queue_locked-->notify_queue_locked;
    notify_queue_locked-->z_sched_wake;
    z_sched_wake-->unpend_thread_no_timeout;
    z_sched_wake-->z_abort_timeout;
    z_sched_wake-->ready_thread;
    z_impl_k_msgq_put-->z_pend_curr;
    zbus_chan_pub-->z_impl_k_sem_give;
    z_impl_k_sem_give-->z_unpend_first_thread;
    z_impl_k_sem_give-->z_ready_thread;
    z_impl_k_sem_give-->z_reschedule;
    z_impl_k_sem_give-->z_handle_obj_poll_events;
    zbus_chan_pub-->__aeabi_read_tp;
    zbus_chan_pub-->z_impl_k_thread_priority_set;
    pub_ota_event-->astarte_individual_from_string;
    astarte_individual_from_string-->memset;
    pub_ota_event-->astarte_individual_from_integer;
    astarte_individual_from_integer-->memset;
    pub_ota_event-->system_time_current_ms;
    system_time_current_ms-->clock_gettime;
    clock_gettime-->z_impl_k_uptime_ticks;
    z_impl_k_uptime_ticks-->sys_clock_tick_get;
    clock_gettime-->__aeabi_uldivmod;
    __aeabi_uldivmod-->__aeabi_idiv0;
    __aeabi_uldivmod-->__udivmoddi4;
    clock_gettime-->z_impl___posix_clock_get_base;
    z_impl___posix_clock_get_base-->__aeabi_read_tp;
    clock_gettime-->__aeabi_read_tp;
    pub_ota_event-->astarte_device_stream_aggregated;
    astarte_device_stream_aggregated-->astarte_device_tx_stream_aggregated;
    astarte_device_tx_stream_aggregated-->introspection_get;
    introspection_get-->find_node_by_name;
    astarte_device_tx_stream_aggregated-->data_validation_aggregated_datastream;
    data_validation_aggregated_datastream-->astarte_interface_get_mapping_from_paths;
    astarte_interface_get_mapping_from_paths-->strlen;
    astarte_interface_get_mapping_from_paths-->calloc;
    astarte_interface_get_mapping_from_paths-->snprintf;
    astarte_interface_get_mapping_from_paths-->astarte_interface_get_mapping_from_path;
    astarte_interface_get_mapping_from_path-->astarte_mapping_check_path;
    astarte_mapping_check_path-->memset;
    astarte_mapping_check_path-->regcomp;
    regcomp-->malloc;
    regcomp-->strlen;
    regcomp-->free;
    regcomp-->memset;
    regcomp-->doemit;
    doemit-->enlarge;
    enlarge-->realloc;
    realloc-->malloc_lock;
    realloc-->sys_heap_aligned_realloc;
    sys_heap_aligned_realloc-->sys_heap_aligned_alloc;
    sys_heap_aligned_realloc-->sys_heap_free;
    sys_heap_aligned_realloc-->mem_to_chunkid;
    sys_heap_aligned_realloc-->chunk_size;
    sys_heap_aligned_realloc-->split_chunks;
    sys_heap_aligned_realloc-->set_chunk_used;
    sys_heap_aligned_realloc-->free_chunk;
    sys_heap_aligned_realloc-->chunk_field;
    sys_heap_aligned_realloc-->free_list_remove;
    sys_heap_aligned_realloc-->free_list_add;
    sys_heap_aligned_realloc-->merge_chunks;
    sys_heap_aligned_realloc-->__aeabi_memcpy;
    realloc-->__aeabi_read_tp;
    realloc-->malloc_unlock;
    enlarge-->seterr;
    seterr-->free;
    regcomp-->p_ere;
    p_ere-->seterr;
    p_ere-->doinsert;
    doinsert-->doemit;
    doinsert-->__aeabi_memmove;
    p_ere-->doemit;
    p_ere-->dofwd;
    p_ere-->p_bracket;
    p_bracket-->realloc;
    p_bracket-->seterr;
    p_bracket-->strncmp;
    p_bracket-->doemit;
    p_bracket-->memset;
    p_bracket-->p_b_coll_elem;
    p_b_coll_elem-->seterr;
    p_b_coll_elem-->strncmp;
    p_bracket-->p_b_symbol;
    p_b_symbol-->seterr;
    p_b_symbol-->p_b_coll_elem;
    p_bracket-->othercase;
    p_bracket-->ordinary;
    ordinary-->othercase;
    ordinary-->p_bracket;
    ordinary-->doemit;
    p_bracket-->freeset;
    p_ere-->ordinary;
    p_ere-->p_count;
    p_count-->seterr;
    p_ere-->repeat;
    repeat-->dupl;
    dupl-->enlarge;
    dupl-->__aeabi_memcpy;
    repeat-->doinsert;
    repeat-->doemit;
    repeat-->dofwd;
    repeat-->seterr;
    regcomp-->realloc;
    regcomp-->seterr;
    regcomp-->ordinary;
    regcomp-->p_bre;
    p_bre-->doemit;
    p_bre-->seterr;
    p_bre-->ordinary;
    p_bre-->p_bracket;
    p_bre-->doinsert;
    p_bre-->dupl;
    p_bre-->p_count;
    p_bre-->repeat;
    regcomp-->altoffset;
    regcomp-->calloc;
    regcomp-->regfree;
    regfree-->free;
    astarte_mapping_check_path-->regexec;
    regexec-->sstep;
    regexec-->strlen;
    regexec-->memcmp;
    regexec-->sslow;
    sslow-->sstep;
    regexec-->malloc;
    regexec-->sdissect;
    sdissect-->sslow;
    regexec-->sbackref;
    sbackref-->memcmp;
    regexec-->free;
    regexec-->memset;
    regexec-->lstep;
    regexec-->__aeabi_memcpy;
    regexec-->lslow;
    lslow-->memset;
    lslow-->lstep;
    lslow-->memcmp;
    lslow-->__aeabi_memcpy;
    regexec-->ldissect;
    ldissect-->lslow;
    regexec-->lbackref;
    lbackref-->memcmp;
    astarte_mapping_check_path-->regfree;
    astarte_interface_get_mapping_from_paths-->free;
    data_validation_aggregated_datastream-->astarte_mapping_check_individual;
    astarte_mapping_check_individual-->__aeabi_dcmpun;
    astarte_mapping_check_individual-->__aeabi_dcmpgt;
    __aeabi_dcmpgt-->__aeabi_cdrcmple;
    __aeabi_cdrcmple-->__aeabi_cdcmpeq;
    __aeabi_cdcmpeq-->__cmpdf2;
    astarte_device_tx_stream_aggregated-->astarte_interface_get_qos;
    astarte_interface_get_qos-->astarte_interface_get_mapping_from_path;
    astarte_device_tx_stream_aggregated-->astarte_bson_serializer_init;
    astarte_bson_serializer_init-->malloc;
    astarte_device_tx_stream_aggregated-->astarte_object_entries_serialize;
    astarte_object_entries_serialize-->astarte_individual_serialize;
    astarte_individual_serialize-->astarte_bson_serializer_append_int32;
    astarte_bson_serializer_append_int32-->byte_array_append_byte;
    byte_array_append_byte-->byte_array_grow;
    byte_array_grow-->malloc;
    byte_array_grow-->abort;
    abort-->printk;
    printk-->vprintk;
    vprintk-->memset;
    vprintk-->__l_vfprintf;
    byte_array_grow-->__aeabi_memcpy;
    byte_array_grow-->free;
    astarte_bson_serializer_append_int32-->strlen;
    astarte_bson_serializer_append_int32-->byte_array_append;
    byte_array_append-->byte_array_grow;
    byte_array_append-->__aeabi_memcpy;
    astarte_individual_serialize-->astarte_bson_serializer_append_int64;
    astarte_bson_serializer_append_int64-->byte_array_append_byte;
    astarte_bson_serializer_append_int64-->strlen;
    astarte_bson_serializer_append_int64-->byte_array_append;
    astarte_individual_serialize-->astarte_bson_serializer_append_double;
    astarte_bson_serializer_append_double-->byte_array_append_byte;
    astarte_bson_serializer_append_double-->strlen;
    astarte_bson_serializer_append_double-->byte_array_append;
    astarte_individual_serialize-->astarte_bson_serializer_append_string;
    astarte_bson_serializer_append_string-->strlen;
    astarte_bson_serializer_append_string-->uint32_to_bytes;
    astarte_bson_serializer_append_string-->byte_array_append_byte;
    astarte_bson_serializer_append_string-->byte_array_append;
    astarte_individual_serialize-->astarte_bson_serializer_append_binary;
    astarte_bson_serializer_append_binary-->uint32_to_bytes;
    astarte_bson_serializer_append_binary-->byte_array_append_byte;
    astarte_bson_serializer_append_binary-->strlen;
    astarte_bson_serializer_append_binary-->byte_array_append;
    astarte_individual_serialize-->astarte_bson_serializer_append_boolean;
    astarte_bson_serializer_append_boolean-->byte_array_append_byte;
    astarte_bson_serializer_append_boolean-->strlen;
    astarte_bson_serializer_append_boolean-->byte_array_append;
    astarte_individual_serialize-->astarte_bson_serializer_append_datetime;
    astarte_bson_serializer_append_datetime-->byte_array_append_byte;
    astarte_bson_serializer_append_datetime-->strlen;
    astarte_bson_serializer_append_datetime-->byte_array_append;
    astarte_individual_serialize-->astarte_bson_serializer_append_int32_array;
    astarte_bson_serializer_append_int32_array-->astarte_bson_serializer_init;
    astarte_bson_serializer_append_int32_array-->astarte_bson_serializer_append_end_of_document;
    astarte_bson_serializer_append_end_of_document-->byte_array_append_byte;
    astarte_bson_serializer_append_end_of_document-->uint32_to_bytes;
    astarte_bson_serializer_append_int32_array-->byte_array_append_byte;
    astarte_bson_serializer_append_int32_array-->strlen;
    astarte_bson_serializer_append_int32_array-->byte_array_append;
    astarte_bson_serializer_append_int32_array-->byte_array_destroy;
    byte_array_destroy-->free;
    astarte_bson_serializer_append_int32_array-->snprintf;
    astarte_bson_serializer_append_int32_array-->astarte_bson_serializer_append_int32;
    astarte_individual_serialize-->astarte_bson_serializer_append_int64_array;
    astarte_bson_serializer_append_int64_array-->astarte_bson_serializer_init;
    astarte_bson_serializer_append_int64_array-->astarte_bson_serializer_append_end_of_document;
    astarte_bson_serializer_append_int64_array-->byte_array_append_byte;
    astarte_bson_serializer_append_int64_array-->strlen;
    astarte_bson_serializer_append_int64_array-->byte_array_append;
    astarte_bson_serializer_append_int64_array-->byte_array_destroy;
    astarte_bson_serializer_append_int64_array-->snprintf;
    astarte_bson_serializer_append_int64_array-->astarte_bson_serializer_append_int64;
    astarte_individual_serialize-->astarte_bson_serializer_append_double_array;
    astarte_bson_serializer_append_double_array-->astarte_bson_serializer_init;
    astarte_bson_serializer_append_double_array-->astarte_bson_serializer_append_end_of_document;
    astarte_bson_serializer_append_double_array-->byte_array_append_byte;
    astarte_bson_serializer_append_double_array-->strlen;
    astarte_bson_serializer_append_double_array-->byte_array_append;
    astarte_bson_serializer_append_double_array-->byte_array_destroy;
    astarte_bson_serializer_append_double_array-->snprintf;
    astarte_bson_serializer_append_double_array-->astarte_bson_serializer_append_double;
    astarte_individual_serialize-->astarte_bson_serializer_append_string_array;
    astarte_bson_serializer_append_string_array-->astarte_bson_serializer_init;
    astarte_bson_serializer_append_string_array-->astarte_bson_serializer_append_end_of_document;
    astarte_bson_serializer_append_string_array-->byte_array_append_byte;
    astarte_bson_serializer_append_string_array-->strlen;
    astarte_bson_serializer_append_string_array-->byte_array_append;
    astarte_bson_serializer_append_string_array-->byte_array_destroy;
    astarte_bson_serializer_append_string_array-->snprintf;
    astarte_bson_serializer_append_string_array-->astarte_bson_serializer_append_string;
    astarte_individual_serialize-->astarte_bson_serializer_append_binary_array;
    astarte_bson_serializer_append_binary_array-->astarte_bson_serializer_init;
    astarte_bson_serializer_append_binary_array-->astarte_bson_serializer_append_end_of_document;
    astarte_bson_serializer_append_binary_array-->byte_array_append_byte;
    astarte_bson_serializer_append_binary_array-->strlen;
    astarte_bson_serializer_append_binary_array-->byte_array_append;
    astarte_bson_serializer_append_binary_array-->byte_array_destroy;
    astarte_bson_serializer_append_binary_array-->snprintf;
    astarte_bson_serializer_append_binary_array-->astarte_bson_serializer_append_binary;
    astarte_individual_serialize-->astarte_bson_serializer_append_boolean_array;
    astarte_bson_serializer_append_boolean_array-->astarte_bson_serializer_init;
    astarte_bson_serializer_append_boolean_array-->astarte_bson_serializer_append_end_of_document;
    astarte_bson_serializer_append_boolean_array-->byte_array_append_byte;
    astarte_bson_serializer_append_boolean_array-->strlen;
    astarte_bson_serializer_append_boolean_array-->byte_array_append;
    astarte_bson_serializer_append_boolean_array-->byte_array_destroy;
    astarte_bson_serializer_append_boolean_array-->snprintf;
    astarte_bson_serializer_append_boolean_array-->astarte_bson_serializer_append_boolean;
    astarte_individual_serialize-->astarte_bson_serializer_append_datetime_array;
    astarte_bson_serializer_append_datetime_array-->astarte_bson_serializer_init;
    astarte_bson_serializer_append_datetime_array-->astarte_bson_serializer_append_end_of_document;
    astarte_bson_serializer_append_datetime_array-->byte_array_append_byte;
    astarte_bson_serializer_append_datetime_array-->strlen;
    astarte_bson_serializer_append_datetime_array-->byte_array_append;
    astarte_bson_serializer_append_datetime_array-->byte_array_destroy;
    astarte_bson_serializer_append_datetime_array-->snprintf;
    astarte_bson_serializer_append_datetime_array-->astarte_bson_serializer_append_datetime;
    astarte_device_tx_stream_aggregated-->astarte_bson_serializer_append_end_of_document;
    astarte_device_tx_stream_aggregated-->astarte_bson_serializer_get_serialized;
    astarte_device_tx_stream_aggregated-->astarte_bson_serializer_destroy;
    astarte_bson_serializer_destroy-->byte_array_destroy;
    astarte_device_tx_stream_aggregated-->astarte_bson_serializer_append_document;
    astarte_bson_serializer_append_document-->byte_array_append_byte;
    astarte_bson_serializer_append_document-->strlen;
    astarte_bson_serializer_append_document-->byte_array_append;
    astarte_device_tx_stream_aggregated-->astarte_bson_serializer_append_datetime;
    astarte_device_tx_stream_aggregated-->publish_data;
    publish_data-->asprintf;
    asprintf-->memset;
    asprintf-->__l_vfprintf;
    asprintf-->realloc;
    asprintf-->free;
    publish_data-->astarte_mqtt_publish;
    astarte_mqtt_publish-->k_mutex_lock;
    k_mutex_lock-->z_impl_k_mutex_lock;
    astarte_mqtt_publish-->mqtt_caching_get_available_message_id;
    mqtt_caching_get_available_message_id-->sys_hashmap_get;
    astarte_mqtt_publish-->mqtt_caching_insert_message;
    mqtt_caching_insert_message-->sys_hashmap_get;
    mqtt_caching_insert_message-->free;
    mqtt_caching_insert_message-->calloc;
    mqtt_caching_insert_message-->strlen;
    mqtt_caching_insert_message-->strncpy;
    strncpy-->memset;
    mqtt_caching_insert_message-->__aeabi_memcpy;
    mqtt_caching_insert_message-->sys_timepoint_calc;
    astarte_mqtt_publish-->memset;
    astarte_mqtt_publish-->strlen;
    astarte_mqtt_publish-->mqtt_publish;
    mqtt_publish-->mqtt_mutex_lock;
    mqtt_mutex_lock-->z_impl_k_mutex_lock;
    mqtt_publish-->tx_buf_init;
    tx_buf_init-->memset;
    mqtt_publish-->verify_tx_state;
    mqtt_publish-->publish_encode;
    publish_encode-->pack_utf8_str;
    pack_utf8_str-->pack_uint16;
    pack_utf8_str-->__aeabi_memcpy;
    publish_encode-->mqtt_encode_fixed_header;
    publish_encode-->pack_uint16;
    mqtt_publish-->memset;
    mqtt_publish-->mqtt_transport_write_msg;
    mqtt_publish-->client_disconnect;
    client_disconnect-->mqtt_transport_disconnect;
    client_disconnect-->memset;
    client_disconnect-->event_notify;
    event_notify-->k_mutex_unlock;
    k_mutex_unlock-->z_impl_k_mutex_unlock;
    event_notify-->mqtt_mutex_lock;
    mqtt_publish-->k_mutex_unlock;
    mqtt_publish-->k_uptime_get_32;
    k_uptime_get_32-->z_impl_k_uptime_ticks;
    k_uptime_get_32-->__aeabi_uldivmod;
    astarte_mqtt_publish-->k_mutex_unlock;
    k_mutex_unlock-->z_impl_k_mutex_unlock;
    publish_data-->free;
    edgehog_ota_init-->edgehog_settings_delete;
    edgehog_settings_delete-->strlen;
    edgehog_settings_delete-->snprintf;
    edgehog_settings_delete-->settings_delete;
    settings_delete-->settings_save_one;
    settings_save_one-->z_impl_k_mutex_lock;
    settings_save_one-->z_impl_k_mutex_unlock;
    edgehog_ota_init-->edgehog_settings_save;
    edgehog_settings_save-->strlen;
    edgehog_settings_save-->snprintf;
    edgehog_settings_save-->settings_save_one;
    edgehog_ota_init-->mcuboot_swap_type;
    mcuboot_swap_type-->boot_swap_type;
    boot_swap_type-->boot_swap_type_multi;
    boot_swap_type_multi-->boot_read_swap_state_by_id;
    boot_read_swap_state_by_id-->flash_area_open;
    boot_read_swap_state_by_id-->boot_read_swap_state;
    boot_read_swap_state-->flash_area_read;
    boot_read_swap_state-->bootutil_buffer_is_erased;
    bootutil_buffer_is_erased-->flash_area_erased_val;
    boot_read_swap_state-->memcmp;
    boot_read_swap_state-->boot_swap_info_off;
    boot_read_swap_state-->boot_read_flag;
    boot_read_flag-->flash_area_read;
    boot_read_flag-->bootutil_buffer_is_erased;
    boot_read_swap_state-->boot_read_image_ok;
    boot_read_image_ok-->boot_read_flag;
    boot_read_swap_state_by_id-->flash_area_close;
    boot_swap_type_multi-->boot_magic_compatible_check;
    edgehog_ota_init-->boot_is_img_confirmed;
    boot_is_img_confirmed-->flash_area_open;
    boot_is_img_confirmed-->boot_read_swap_state;
    edgehog_ota_init-->boot_write_img_confirmed;
    boot_write_img_confirmed-->flash_area_open;
    boot_write_img_confirmed-->boot_set_next;
    boot_set_next-->boot_read_swap_state;
    boot_set_next-->boot_write_image_ok;
    boot_write_image_ok-->boot_write_trailer_flag;
    boot_write_trailer_flag-->boot_write_trailer;
    boot_write_trailer-->flash_area_align;
    boot_write_trailer-->flash_area_erased_val;
    boot_write_trailer-->__aeabi_memcpy;
    boot_write_trailer-->memset;
    boot_write_trailer-->flash_area_write;
    boot_set_next-->boot_write_magic;
    boot_write_magic-->flash_area_erased_val;
    boot_write_magic-->flash_area_write;
    boot_set_next-->boot_write_swap_info;
    boot_write_swap_info-->boot_swap_info_off;
    boot_write_swap_info-->boot_write_trailer;
    boot_set_next-->flash_area_erase;
    boot_write_img_confirmed-->flash_area_close;
    edgehog_device_start-->publish_hardware_info;
    publish_hardware_info-->astarte_individual_from_string;
    publish_hardware_info-->astarte_device_set_property;
    astarte_device_set_property-->astarte_device_tx_set_property;
    astarte_device_tx_set_property-->introspection_get;
    astarte_device_tx_set_property-->data_validation_set_property;
    data_validation_set_property-->data_validation_individual_datastream;
    data_validation_individual_datastream-->astarte_interface_get_mapping_from_path;
    data_validation_individual_datastream-->astarte_mapping_check_individual;
    astarte_device_tx_set_property-->astarte_device_caching_property_store;
    astarte_device_caching_property_store-->memset;
    astarte_device_caching_property_store-->open_kv_storage;
    open_kv_storage-->z_impl_device_is_ready;
    open_kv_storage-->z_impl_flash_get_page_info_by_offs;
    open_kv_storage-->astarte_kv_storage_init;
    astarte_kv_storage_init-->strlen;
    astarte_kv_storage_init-->calloc;
    astarte_kv_storage_init-->strncpy;
    astarte_device_caching_property_store-->strlen;
    astarte_device_caching_property_store-->calloc;
    astarte_device_caching_property_store-->snprintf;
    astarte_device_caching_property_store-->astarte_bson_serializer_init;
    astarte_device_caching_property_store-->astarte_bson_serializer_append_int32;
    astarte_device_caching_property_store-->astarte_bson_serializer_append_int64;
    astarte_device_caching_property_store-->astarte_individual_serialize;
    astarte_device_caching_property_store-->astarte_bson_serializer_append_end_of_document;
    astarte_device_caching_property_store-->astarte_bson_serializer_get_serialized;
    astarte_device_caching_property_store-->astarte_kv_storage_insert;
    astarte_kv_storage_insert-->memset;
    astarte_kv_storage_insert-->k_mutex_lock;
    k_mutex_lock-->z_impl_k_mutex_lock;
    astarte_kv_storage_insert-->nvs_mount;
    astarte_kv_storage_insert-->k_mutex_unlock;
    k_mutex_unlock-->z_impl_k_mutex_unlock;
    astarte_kv_storage_insert-->get_stored_pairs;
    get_stored_pairs-->nvs_read;
    astarte_kv_storage_insert-->find_pair_base_id;
    find_pair_base_id-->get_nvs_entry_with_alloc;
    get_nvs_entry_with_alloc-->get_nvs_entry;
    get_nvs_entry-->nvs_read;
    get_nvs_entry_with_alloc-->calloc;
    get_nvs_entry_with_alloc-->free;
    find_pair_base_id-->strcmp;
    find_pair_base_id-->free;
    astarte_kv_storage_insert-->insert_pair_at;
    insert_pair_at-->strlen;
    insert_pair_at-->nvs_write;
    nvs_write-->nvs_al_size;
    nvs_write-->nvs_prev_ate;
    nvs_write-->nvs_ate_valid;
    nvs_write-->nvs_flash_rd;
    nvs_write-->memcmp;
    nvs_write-->z_impl_k_mutex_lock;
    nvs_write-->nvs_flash_al_wrt;
    nvs_write-->nvs_ate_crc8_update;
    nvs_write-->nvs_flash_ate_wrt;
    nvs_write-->z_impl_k_mutex_unlock;
    nvs_write-->nvs_sector_advance;
    nvs_write-->nvs_gc;
    astarte_kv_storage_insert-->nvs_write;
    astarte_device_caching_property_store-->free;
    astarte_device_caching_property_store-->astarte_bson_serializer_destroy;
    astarte_device_tx_set_property-->astarte_device_tx_stream_individual;
    astarte_device_tx_stream_individual-->introspection_get;
    astarte_device_tx_stream_individual-->data_validation_individual_datastream;
    astarte_device_tx_stream_individual-->astarte_interface_get_qos;
    astarte_device_tx_stream_individual-->astarte_bson_serializer_init;
    astarte_device_tx_stream_individual-->astarte_individual_serialize;
    astarte_device_tx_stream_individual-->astarte_bson_serializer_append_datetime;
    astarte_device_tx_stream_individual-->astarte_bson_serializer_append_end_of_document;
    astarte_device_tx_stream_individual-->astarte_bson_serializer_get_serialized;
    astarte_device_tx_stream_individual-->publish_data;
    astarte_device_tx_stream_individual-->astarte_bson_serializer_destroy;
    publish_hardware_info-->astarte_individual_from_longinteger;
    astarte_individual_from_longinteger-->memset;
    edgehog_device_start-->publish_os_info;
    publish_os_info-->astarte_individual_from_string;
    publish_os_info-->astarte_device_set_property;
    publish_os_info-->sys_kernel_version_get;
    publish_os_info-->snprintf;
    edgehog_device_start-->publish_system_info;
    edgehog_device_start-->publish_base_image;
    publish_base_image-->astarte_individual_from_string;
    publish_base_image-->astarte_device_set_property;
    edgehog_device_start-->publish_runtime_info;
    publish_runtime_info-->astarte_individual_from_string;
    publish_runtime_info-->astarte_device_set_property;
    publish_runtime_info-->snprintf;
    publish_runtime_info-->sys_kernel_version_get;
    publish_runtime_info-->memset;
    edgehog_device_start-->publish_system_status;
    publish_system_status-->k_thread_foreach_unlocked;
    publish_system_status-->hardware_info_get_memory_size;
    publish_system_status-->astarte_individual_from_longinteger;
    publish_system_status-->astarte_individual_from_string;
    publish_system_status-->astarte_individual_from_integer;
    publish_system_status-->z_impl_k_uptime_ticks;
    publish_system_status-->__aeabi_uldivmod;
    publish_system_status-->system_time_current_ms;
    publish_system_status-->astarte_device_stream_aggregated;
    edgehog_device_start-->publish_storage_usage;
    publish_storage_usage-->edgehog_nvs_get_free_space;
    edgehog_nvs_get_free_space-->edgehog_nvs_open;
    edgehog_nvs_open-->z_impl_device_is_ready;
    edgehog_nvs_open-->z_impl_flash_get_page_info_by_offs;
    edgehog_nvs_open-->nvs_mount;
    edgehog_nvs_get_free_space-->nvs_calc_free_space;
    nvs_calc_free_space-->nvs_al_size;
    nvs_calc_free_space-->nvs_prev_ate;
    nvs_calc_free_space-->nvs_ate_valid;
    publish_storage_usage-->astarte_individual_from_longinteger;
    publish_storage_usage-->system_time_current_ms;
    publish_storage_usage-->astarte_device_stream_aggregated;
    edgehog_device_start-->edgehog_telemetry_start;
    edgehog_telemetry_start-->k_msgq_init;
    edgehog_telemetry_start-->z_impl_k_thread_create;
    z_impl_k_thread_create-->z_setup_new_thread;
    z_setup_new_thread-->memset;
    z_setup_new_thread-->arch_tls_stack_setup;
    arch_tls_stack_setup-->__aeabi_memcpy;
    arch_tls_stack_setup-->memset;
    z_setup_new_thread-->arch_new_thread;
    z_impl_k_thread_create-->z_sched_start;
    z_sched_start-->ready_thread;
    z_sched_start-->z_reschedule;
    z_impl_k_thread_create-->z_add_timeout;
    edgehog_telemetry_start-->telemetry_schedule_entry;
    telemetry_schedule_entry-->store_telemetry_entry;
    store_telemetry_entry-->snprintf;
    store_telemetry_entry-->edgehog_settings_save;
    telemetry_schedule_entry-->k_timer_remaining_get;
    k_timer_remaining_get-->z_timeout_remaining;
    z_timeout_remaining-->timeout_rem;
    z_timeout_remaining-->elapsed;
    k_timer_remaining_get-->__aeabi_uldivmod;
    telemetry_schedule_entry-->z_impl_k_timer_start;
    z_impl_k_timer_start-->z_abort_timeout;
    z_impl_k_timer_start-->z_add_timeout;
    telemetry_schedule_entry-->z_impl_k_timer_stop;
    z_impl_k_timer_stop-->z_abort_timeout;
    z_impl_k_timer_stop-->z_unpend1_no_timeout;
    z_unpend1_no_timeout-->unpend_thread_no_timeout;
    z_impl_k_timer_stop-->z_ready_thread;
    z_impl_k_timer_stop-->z_reschedule_irqlock;
    telemetry_schedule_entry-->free;
    edgehog_device_thread_entry_point-->k_sleep;
    k_sleep-->z_impl_k_sleep;
    z_impl_k_sleep-->z_impl_k_thread_suspend;
    z_impl_k_thread_suspend-->z_abort_timeout;
    z_impl_k_thread_suspend-->z_thread_halt;
    z_thread_halt-->update_cache;
    z_thread_halt-->arch_swap;
    z_thread_halt-->sys_dlist_remove;
    z_thread_halt-->unpend_thread_no_timeout;
    z_thread_halt-->z_abort_timeout;
    z_thread_halt-->ready_thread;
    z_thread_halt-->z_thread_monitor_exit;
    z_impl_k_sleep-->z_tick_sleep;
    z_tick_sleep-->z_impl_k_yield;
    z_impl_k_yield-->sys_dlist_remove;
    z_impl_k_yield-->update_cache;
    z_impl_k_yield-->arch_swap;
    z_tick_sleep-->sys_clock_tick_get_32;
    sys_clock_tick_get_32-->sys_clock_tick_get;
    z_tick_sleep-->unready_thread;
    z_tick_sleep-->z_add_timeout;
    z_tick_sleep-->arch_swap;
    z_impl_k_sleep-->__aeabi_uldivmod;
    edgehog_device_thread_entry_point-->edgehog_device_stop;
    edgehog_device_stop-->edgehog_telemetry_stop;
    edgehog_telemetry_stop-->z_impl_k_thread_join;
    z_impl_k_thread_join-->add_to_waitq_locked;
    z_impl_k_thread_join-->z_add_timeout;
    z_impl_k_thread_join-->arch_swap;
    edgehog_device_thread_entry_point-->edgehog_device_destroy;
    edgehog_device_destroy-->edgehog_telemetry_destroy;
    edgehog_device_destroy-->free;
