# (C) Copyright 2026, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

import json
from pathlib import Path
from typing import Any, Optional, Union

import pytest
from astarte.device import Interface
from dotenv import dotenv_values
from twister_harness import DeviceAdapter, Shell


class MissingConfigError(Exception):
    def __init__(self, key: str) -> None:
        super().__init__(f"Missing required configuration value for key: {key}")


class Configuration:
    dut: DeviceAdapter
    shell: Shell
    realm: str
    device_id: str
    appengine_url: str
    appengine_token: str
    appengine_cert: Path
    log_only: bool
    interfaces: list[Interface]

    def __init__(
        self, config_file_path: Union[str, Path], dut: DeviceAdapter, shell: Shell
    ) -> None:
        self.dut = dut
        self.shell = shell

        prj_config: dict[str, Optional[str]] = dotenv_values(config_file_path)

        self.realm = self._get_config_value(prj_config, "CONFIG_ASTARTE_DEVICE_SDK_REALM_NAME")
        self.device_id = self._get_config_value(prj_config, "CONFIG_ASTARTE_DEVICE_ID")
        self.appengine_url = self._get_config_value(prj_config, "CONFIG_E2E_APPENGINE_URL")
        self.appengine_token = self._get_config_value(prj_config, "CONFIG_E2E_APPENGINE_TOKEN")

        cert_path: str = self._get_config_value(prj_config, "CONFIG_TLS_CERTIFICATE_PATH")
        self.appengine_cert = Path(__file__).resolve().parents[1] / cert_path

        try:
            self.log_only = self._get_config_value(prj_config, "CONFIG_LOG_ONLY").lower() == "y"
        except MissingConfigError:
            self.log_only = False

        interfaces_rel_dir: str = self._get_config_value(
            prj_config, "CONFIG_ASTARTE_DEVICE_SDK_ADVANCED_CODE_GENERATION_INTERFACE_DIRECTORY"
        )
        interfaces_dir: Path = Path(__file__).resolve().parents[1] / interfaces_rel_dir

        self.interfaces = []

        interface_file: Path
        for interface_file in sorted([i for i in interfaces_dir.iterdir() if i.suffix == ".json"]):
            with open(interface_file, "r", encoding="utf-8") as interface_fp:
                interface_json: dict[str, Any] = json.load(interface_fp)
                self.interfaces.append(Interface(interface_json))

    @staticmethod
    def _get_config_value(config: dict[str, Optional[str]], key: str) -> str:
        value: Optional[str] = config.get(key)

        if value is None or not value:
            raise MissingConfigError(key)

        # Strip literal quotes generated by Zephyr Kconfig
        return value.strip('"')


@pytest.fixture(scope="session")
def end_to_end_configuration(dut: DeviceAdapter, shell: Shell) -> Configuration:
    cfg_file: Path = Path(dut.device_config.build_dir) / "zephyr" / ".config"
    return Configuration(cfg_file, dut, shell)
